server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/renlle/microservicecloud-config.git #Gitee 上面的git仓库http地址
#          uri: git@gitee.com:renlle/microservicecloud-config.git #Gitee 上面的git仓库SSH
          #          uri: git@github.com:zzyybs/microservicecloud-config.git #GitHub上面的git仓库名字

