server:
  port: 9527

spring:                                                    #对应Eureka的微服务名字
   application:
      name:  microservicecloud-zuul-gateway
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
      username: szs
      password: 1234
      dbcp2:
        min-idle: 5                                           # 数据库连接池的最小维持连接数
        initial-size: 5                                       # 初始化连接数
        max-total: 5                                          # 最大连接数
        max-wait-millis: 200                                  # 等待连接获取的最大超时时间
info:
  app.name: szs-microservicecloud
  company.name: www.szs.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka    #单机版,下面为集群版
       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com  # 主机映射名称修改(自定义hystrix服务名称信息)
    prefer-ip-address: true     #访问路径可以显示IP地址,可公共访问的IP地址
# 配置网关zuul映射
zuul:
  routes:
    mydept.serviceId: microservicecloud-provider-dept  #真实服务提供名
    mydept.path: /mydept/**                              #假的映射路径
  ignored-services: "*"                                #忽略全部
  prefix: /szs

